pool:
  vmImage: ubuntu-16.04

steps:
  - task: UsePythonVersion@0
    inputs:
      architecture: x64
      versionSpec: '3.7'

  - script: |
      python -m venv .venv
      source .venv/bin/activate
    displayName: 'Setup virtual environment'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements.freeze.txt
      pip install --upgrade unittest-xml-reporting
    displayName: 'Install prerequisites'

  - script: |
      python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testRunTitle: 'Python $(PYTHON_VERSION)'
      testResultsFiles: '**/TEST-*.xml'
    condition: succeededOrFailed()
