pool:
  vmImage: ubuntu-16.04

variables:
  pythonVersion: '3.7'
  imageName: 'drisk/mock-api-gateway'
  latestImage: '$(imageName):latest'
  versionedImage: '$(imageName):$(Build.BuildId)'
  awsRegion: '268927183565.dkr.ecr.ap-southeast-1.amazonaws.com'

steps:
  - task: UsePythonVersion@0
    inputs:
      architecture: x64
      versionSpec: $(pythonVersion)

  - bash: |
      python -m venv .venv
      source .venv/bin/activate
    displayName: 'Setup virtual environment'

  - bash: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements.freeze.txt
    displayName: 'Install prerequisites'

  - bash: |
      python manage.py migrate
    displayName: 'Initialize db.sqlite3'

  - bash: |
      pip install --upgrade unittest-xml-reporting
      python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    displayName: 'Run tests for Python $($pythonVersion)'

  - task: PublishTestResults@2
    inputs:
      testRunTitle: 'Test results for Python $($pythonVersion)'
      testResultsFiles: '**/TEST-*.xml'
    condition: succeededOrFailed()

  - bash: |
      python manage.py populatedb --companies 100 --singtel
      docker build --tag $(imageName) .
      docker push $(awsRegion)/$(imageName)
    displayName: 'Build Docker image'
    condition: succeededOrFailed()
